<?php

/** Page Attachements **/
function hmp_track_page_attachments(array &$attachments) {
	$hmp_track = \Drupal::state()->get('hmp_track');
	$attachments['#attached']['drupalSettings']['hmp_track'] = $hmp_track;
  	$attachments['#attached']['library'][] = 'hmp_track/hmp_track';
}

/** Dynamic Libraries **/
function hmp_track_library_info_build() {
	$libraries = [];
	$hmp_track = \Drupal::state()->get('hmp_track');
	if($hmp_track['proclivity_px'] != '') {
		$libraries['hmp_track'] = [
			'js' => [
				$hmp_track['proclivity_px'] => [],
			]
		];
	}
	return $libraries;
}

/** **/